<?php
// Available variables
$imagePath = $this->imagePath;
$book = $this->book;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Cover</title>
  <style type="text/css">
  <!-- cover page styles go here -->
  </style>
</head>
<body id="coverPage">
  <div class="coverInside">
    <img src="<?php print $imagePath ?>" alt="CoverImage" />
  </div>
</body>
</html>