<?php
// Available variables
$book = $this->book;
print "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="../css/sys/labsys_epub_theme.css" />
  <title>Cover Page</title>
</head>
<body id="frontMatter">
<?php
  if ($book->getOption('imprint')){
    echo( '<div class="pageBreakAfter"><div class="imprint">'.$book->getOption('imprint').'</div></div>' );
  }
/*
  if ($book->getOption('otherOption')){
    echo( '<div class="pageBreakAfter"><div class="otherOption style from /css/sys/labsystem_epub.css">'.$book->getOption('otherOption').'</div></div>' );
  }
*/
?>


</body>
</html>