<?php
// Available variables
$book = $this->book;
?>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="../css/sys/labsys_epub_theme.css" />
  <title>Cover Page</title>
</head>
<body id="frontMatter">
  <div class="pageBreakAfter">
      <?php if ($book->getOption('imprint')): ?>
      <?php echo( '<div class="pageBreakAfter"><div class="imprint">'.$book->getOption('imprint').'</div></div>' ); ?>
      <?php endif; ?>
  </div>
</body>
</html>