<?php
// Available variables
$book = $this->book;
?>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="../css/sys/labsys_epub_theme.css" />
  <title>Cover Page</title>
</head>
<body id="frontMatter">
<?php
  if ($book->getOption('imprint')){
    echo( '<div class="pageBreakAfter"><div class="imprint">'.$book->getOption('imprint').'</div></div>' );
  }
/*
  if ($book->getOption('otherOption')){
    echo( '<div class="pageBreakAfter"><div class="otherOption style from /css/sys/labsystem_epub.css">'.$book->getOption('otherOption').'</div></div>' );
  }
*/
?>


</body>
</html>