<?php
// Available variables
$imagePath = $this->imagePath;
$book = $this->book;
?>
<html>
<head>
  <title>Cover Page</title>
</head>
<body id="coverAndImprint">
  <div class="coverInside">
    <img src="<?php print $imagePath ?>" />
  </div>
  <div class="pageBreakAfter">
    Now it should break... but it does not.
  </div>
  <?php if ($book->getOption('imprint')): ?>
  <?php echo( '<div class="pageBreakAfter"><div class="imprint">'.$book->getOption('imprint').'</div></div>' ); ?>
  <?php endif; ?>
</body>
</html>