<?php

/**
* This module contains configuration variables; rename to config.inc and change
* the values as required
*
* @module     ../include/config.inc
*/

$ERRORMAIL_RECEIVER = ''; // this email address will receive error messages
$DEFAULT_INSTANCE = ''; // this instance will be used if no config= parameter was given
$SYSTEMMAIL_SENDER = ''; // used to send all mails (the student mail is used as reply-to if available

?>
